/** This AstStatement is not generated by the parser.
    Instead, it is generated at a later phase, usually compile time.
    It is used for hooking up functions that are defined in the compiler,
    likely functions that will output more executable code into
    to the program.

    If any of the functions are empty they will not be called.
*/

#ifndef AST_GENERATED_STATEMENT_HPP
#define AST_GENERATED_STATEMENT_HPP

#include <ace-c/ast/ast_statement.hpp>

#include <functional>

typedef std::function<void(AstVisitor*, Module*)> CompilerFunction_t;

class AstGeneratedStatement : public AstStatement {
public:
    AstGeneratedStatement(CompilerFunction_t on_visit,
        CompilerFunction_t on_build,
        CompilerFunction_t on_optimize,
        const SourceLocation &location);
    virtual ~AstGeneratedStatement() = default;

    virtual void Visit(AstVisitor *visitor, Module *mod) override;
    virtual void Build(AstVisitor *visitor, Module *mod) override;
    virtual void Optimize(AstVisitor *visitor, Module *mod) override;

protected:
    CompilerFunction_t m_on_visit;
    CompilerFunction_t m_on_build;
    CompilerFunction_t m_on_optimize;
};

#endif